import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navegation from "../components/Navegation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white text-gray-600 work-sans leading-normal text-base tracking-normal">
        <Navegation />
        {children}
      </body>
    </html>
  );
}
